export declare const firebaseConfig: any;
export declare const projectId: any;
export declare const emulator: boolean;
export declare const isBeta: boolean;
export declare const adTest: boolean;
export declare const domain: string;
export declare const userUrl: string;
export declare const mainUrl: string;
export declare const gtag: string;
export declare const corsOrigin: string[];
export declare const corsAmp = "https://fabricelements-co.cdn.ampproject.org";
